---
- name: make a build dir
  file: state=directory name=/root/icinga2-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/icinga2-dockerized/Dockerfile

- name: put ido configs
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: icinga2-ido-mysql.conf, dest: /root/icinga2-dockerized/icinga2-ido-mysql.conf }
    - { src: ido-mysql.conf, dest: /root/icinga2-dockerized/ido-mysql.conf }

- name: put icinga2.rb
  template: src=icinga2.rb dest=/root/icinga2-dockerized/icinga2.rb

- name: put createdb.sh
  template: src=createdb.sh dest=/root/icinga2-dockerized/createdb.sh mode=0755

- name: build a Docker image for icinga2
  docker_image: path="/root/icinga2-dockerized" name="gitinsky/icinga2" tag="0.0.1" state="build"

- name: tag it as latest
  command: docker tag -f gitinsky/icinga2:0.0.1 gitinsky/icinga2:latest
